version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: terrabovina_db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: terrabovina_db
      MYSQL_USER: terrabovina_user
      MYSQL_PASSWORD: terrabovina_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
